### ISSUE TITLE
usb设备不识别

### ISSUE THREAD

**Issue by Zeh868** [longtengmcu/USB-HOST-driver-4G-rndis-device#2]
![image](https://user-images.githubusercontent.com/53844299/192691039-46828410-bc02-46df-ae18-6b554b075716.png)
你好，设备枚举过程中，不识别usb设备，
log是获取不到header的描述符。请问是不是您改过USB_core.c的礼拜？

**Comment by longtengmcu** [comment]
你目前使用的是代码是在这个仓库中上下载的，如果是的话应该是可以使用，能枚举到设备的。

从 Windows 版邮件发送

发件人: QZehao
发送时间: 2022年9月28日 12:58
收件人: longtengmcu/USB-HOST-driver-4G-rndis-device
抄送: Subscribed
主题: [longtengmcu/USB-HOST-driver-4G-rndis-device] usb设备不识别 (Issue #2)


你好，设备枚举过程中，不识别usb设备，
log是获取不到header的描述符。请问是不是您改过USB_core.c的礼拜？

**Comment by Zeh868** [comment]
![image](https://user-images.githubusercontent.com/53844299/192782596-58a88f73-7185-437b-ab15-4c9e6785e579.png)
我把这个if注释掉   就可以枚举到了，但是会出现很多NAK

**Comment by longtengmcu** [comment]
usb_core相对于原来的rtthread中是修改过。你测试的环境如果是stm32f429+L501模组这样的环境是可以识别到模组的，如果不是这样的环境可能要修改usb驱动程序了。

**Comment by Zeh868** [comment]
我的测试环境是STM32F407，跟你这个是一个系列的。我用的模组是RM510Q-GL

**Comment by Zeh868** [comment]
最新进展：
描述符拿到并解析成功了，但是调用到rt_rndis_run里的rt_rndis_msg_init时  失败了。
失败的过程如图：
![image](https://user-images.githubusercontent.com/53844299/193205383-427cf740-e25c-4530-bba3-6667e9a54c48.png)

**Comment by longtengmcu** [comment]
RM510Q模组没有对接过，这个需要你去调整和优化USB驱动程序部分

**Comment by longtengmcu** [comment]
USB驱动程序问题，需要调整驱动程序

**Comment by longtengmcu** [comment]
USB驱动程序问题
