### ISSUE TITLE
与RNDIS网卡数据无法正常发送接收

### ISSUE THREAD

**Issue by Zeh868** [longtengmcu/USB-HOST-driver-4G-rndis-device#3]
![image](https://user-images.githubusercontent.com/53844299/194530666-551c39b6-ba28-4730-aac5-c0816be3d119.png)
![image](https://user-images.githubusercontent.com/53844299/194530975-b7a69f02-b7ff-4db7-bf49-d8c9196aade7.png)
楼主好，再次打扰；
接口我调通了，枚举也成功了，同时也获得了网卡的mac地址，但是做DHCP协商的时候，发现rt_rndis_eth_tx这个函数（即把协议栈过来的数据发送至网卡中的接口函数），把数据交给data interface的ep时，直接nak了，就一直没成功过。请问是我哪里还没适配好，还是HAL_HCD_HC_SubmitRequest这个接口出了问题？

**Comment by longtengmcu** [comment]
我估计还是st的驱动程序的问题发自我的荣耀手机-------- 原始邮件 --------发件人： QZehao ***@***.***>日期： 2022年10月7日周五 18:19收件人： longtengmcu/USB-HOST-driver-4G-rndis-device ***@***.***>抄送： Subscribed ***@***.***>主    题： [longtengmcu/USB-HOST-driver-4G-rndis-device] 与RNDIS网卡数据无法正常发送接收 (Issue #3)





楼主好，再次打扰；

接口我调通了，枚举也成功了，同时也获得了网卡的mac地址，但是做DHCP协商的时候，发现rt_rndis_eth_tx这个函数（即把协议栈过来的数据发送至网卡中的接口函数），把数据交给data interface的ep时，直接nak了，就一直没成功过。请问是我哪里还没适配好，还是HAL_HCD_HC_SubmitRequest这个接口出了问题？

**Comment by longtengmcu** [comment]
USB驱动程序问题
