### ISSUE TITLE
rt_rndis_eth_rx

### ISSUE THREAD

**Issue by chenzhihong007** [longtengmcu/USB-HOST-driver-4G-rndis-device#4]
您好！在component/drivers/usb/usbhost/class/rndis_dev.c中rt_rndis_eth_rx()该函数内部第1056行和component/drivers/usb/usbdevice/class/rndis.c中，rt_rndis_eth_rx()函数内部1107行，allocate buffer如下：

![image](https://github.com/longtengmcu/USB-HOST-driver-4G-rndis-device/assets/109498998/888e78a7-10bc-46d4-bc20-544630e55eff)

请问下这里的layer为什么不是PBUF_RAW？rndis data msg应该包含链路层的Header信息，我觉得allocate buffer应该类似于这样写：
![image](https://github.com/longtengmcu/USB-HOST-driver-4G-rndis-device/assets/109498998/17fcfcb8-5d0d-47e6-937a-97c2ccb0ddf6)

不知我上述理解是否正确，请指正，谢谢！

**Comment by longtengmcu** [comment]
按你的写法使用PBUF_RAW也是可以的，这里我使用PBUF_LINK可能有点想用程序代码直接说明这种网络数据是与来自于硬件PHY接口的数据不一样而已。
